### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [MrBacon470/Coop-Co#31] opened 2023-12-15 18:06 UTC
just looks like this upon loading 
![image](https://github.com/MrBacon470/Coop-Co/assets/101602826/c6ce596e-5900-4f68-95de-5654df2a6021)
(I am aware this seems to be an issue with trying to update it, I have no idea if this is helpful though.)
Clicking on the buttons doesn't work, and  I can scroll to the bottom. Hovering over the buttons highlights them but doesn't react to clicking

**Comment by VoidCloud04** [comment] 2023-12-15 19:11
Yes the game is currently down due to deployment errors.

**Comment by VoidCloud04** [comment] 2023-12-15 19:18
All Scripts & Images are failing to load to the game annoyingly enough

**Comment by ExplodingHairyPotatoCat** [comment] 2023-12-15 19:28
Oh that sucks, any ideas as to why?

**Comment by VoidCloud04** [comment] 2023-12-15 19:32
I'm trying to figure that out as both the official astro build action isn't working its just giving a 404 & the hacky solution gives me that problem

**Comment by VoidCloud04** [comment] 2023-12-15 19:32
Currently Troubleshooting may end up taking a while to get it to work :/

**Comment by ExplodingHairyPotatoCat** [comment] 2023-12-15 19:37
What if you tried renaming the page and then depoloying the astro build?

**Comment by VoidCloud04** [comment] 2023-12-15 19:39
The problem is the github pages site fails to request the site itself then it gives a Content Security Policy Error

**Comment by VoidCloud04** [comment] 2023-12-15 20:11
Should be finally fixed now

**Closed as completed by VoidCloud04** 2023-12-15 20:11 UTC
Labels: bug, developer issue
